use bitflags::bitflags;

bitflags! {
	/// Flags applying to this frame.
	pub(super) struct Flags: u8 {
		/// Compression flag.
		/// If set, the frame body is compressed. The actual compression to use should have been set
		/// up beforehand through the Startup message.
		const Compression = 1 << 0;
		/// Tracing flag.
		/// For a request frame, this indicates the client requires tracing of the request. Note
		/// that only QUERY, PREPARE and EXECUTE queries support tracing. Other requests will simply
		/// ignore the tracing flag if set. If a request supports tracing and the tracing flag is
		/// set, the response to this request will have the tracing flag set and contain tracing
		/// information.
		/// If a response frame has the tracing flag set, its body contains a tracing ID. The
		/// tracing ID is a [uuid] and is the first thing in the frame body.
		const Tracing = 1 << 1;
		/// Custom payload flag.
		/// For a request or response frame, this indicates that a generic key-value custom payload
		/// for a custom QueryHandler implementation is present in the frame. Such a custom payload
		/// is simply ignored by the default QueryHandler implementation. Currently, only QUERY,
		/// PREPARE, EXECUTE and BATCH requests support payload. Type of custom payload is
		/// [bytes map]. If either or both of the tracing and warning flags are set, the custom
		/// payload will follow those indicated elements in the frame body. If neither are set, the
		/// custom payload will be the first value in the frame body.
		const Custom = 1 << 2;
		/// Warning flag.
		/// The response contains warnings which were generated by the server to go along with this
		/// response. If a response frame has the warning flag set, its body will contain the text
		/// of the warnings. The warnings are a [string list] and will be the first value in the
		/// frame body if the tracing flag is not set, or directly after the tracing ID if it is.
		const Warning = 1 << 3;
		// The rest of flags is currently unused and ignored.
	}
}

impl TryFrom<u8> for Flags {
	type Error = u8;

	fn try_from(flags: u8) -> Result<Self, Self::Error> {
		Flags::from_bits(flags).ok_or(flags)
	}
}
