#![allow(static_mut_refs)]

use crate::maps::PIDS;
use aya_ebpf::{
	bindings::{BPF_TCP_CLOSE_WAIT, BPF_TCP_ESTABLISHED},
	helpers::bpf_get_current_pid_tgid,
};
use ebpf_common::{
	co_re::{sock_type, socket, task_struct, tcp_sock},
	core_read_kernel,
	error::{Result, code::*},
};
use observ_trace_common::{L4Protocol, Quintuple, SaFamily};

/// Check if the pid is in pid_map, which is generated by agent at user space
#[inline(always)]
pub(crate) fn is_filtered_pid() -> bool {
	let tgid = (bpf_get_current_pid_tgid() >> 32) as u32;
	unsafe { PIDS.get_ptr(&tgid) }.is_some()
}

#[inline(always)]
pub(crate) fn is_tcp_udp(sock: tcp_sock) -> Result<L4Protocol> {
	let ipv6only = core_read_kernel!(sock, inet_conn, icsk_inet, sk, __sk_common, skc_ipv6only)?;
	let skc_family =
		SaFamily::from(core_read_kernel!(sock, inet_conn, icsk_inet, sk, __sk_common, skc_family)?);
	match skc_family {
		SaFamily::AF_INET if ipv6only == 0 => {},
		// TODO: add ipv4_mapped_to_ipv6 check
		SaFamily::AF_INET6 => {},
		_ => return Err(NOT_IP_PROTOCOL),
	}
	let sk_type =
		sock_type::from(core_read_kernel!(sock, inet_conn, icsk_inet, sk, sk_type)? as i16);
	match sk_type {
		sock_type::SOCK_DGRAM => Ok(L4Protocol::IPPROTO_UDP),
		sock_type::SOCK_STREAM => {
			let skc_state =
				core_read_kernel!(sock, inet_conn, icsk_inet, sk, __sk_common, skc_state)? as u32;
			// If the connection has not been established yet, and it is not in the `ESTABLISHED` or `CLOSE_WAIT` state, exit.
			if skc_state != BPF_TCP_ESTABLISHED && skc_state != BPF_TCP_CLOSE_WAIT {
				return Err(SOCKET_STATE_INVALID);
			}
			Ok(L4Protocol::IPPROTO_TCP)
		},
		_ => Err(NOT_TCPUDP),
	}
}

#[inline(always)]
pub(crate) fn gen_connect_key(high: u64, low: u64) -> u64 {
	(high & 0xFFFFFFFF00000000) | (low & 0x00000000FFFFFFFF)
}
#[inline(always)]
pub(crate) fn tcp_sock_from_fd(fd: u64) -> Result<tcp_sock> {
	let current = task_struct::current();
	let file = match current.get_fd(fd as usize) {
		Some(f) => f,
		None => return Err(READ_FILE_FAILED),
	};
	if file.is_null() {
		return Err(FILE_PTR_NULL);
	}
	let socket = socket::from_ptr(core_read_kernel!(file, private_data)? as *const _);
	if !socket.is_valid_type() {
		return Err(SOCKET_TYPE_NOT_SUPPORTED);
	}
	Ok(tcp_sock::from_ptr(core_read_kernel!(socket, sk)?.as_ptr() as *const _))
}

#[inline(always)]
pub(crate) fn read_seq(fd: u64) -> Result<u32> {
	let sock = tcp_sock_from_fd(fd)?;
	Ok(core_read_kernel!(sock, copied_seq)?)
}
#[inline(always)]
pub(crate) fn write_seq(fd: u64) -> Result<u32> {
	let sock = tcp_sock_from_fd(fd)?;
	Ok(core_read_kernel!(sock, write_seq)?)
}
#[inline(always)]
pub fn quintuple_from_sock(tcp_sock: tcp_sock) -> Result<Quintuple> {
	let src_addr = core_read_kernel!(tcp_sock, inet_conn, icsk_inet, inet_saddr)?.to_be();
	let sock_common = core_read_kernel!(tcp_sock, inet_conn, icsk_inet, sk, __sk_common)?;
	let dst_addr = sock_common.skc_daddr().ok_or(READ_SKC_DADDR_FAILED)?.to_be();
	let src_port = core_read_kernel!(tcp_sock, inet_conn, icsk_inet, inet_sport)?.to_be();
	let dst_port = sock_common.skc_dport().ok_or(READ_SKC_DPORT_FAILED)?.to_be();
	let skc_family = sock_common.skc_family().ok_or(READ_SKC_FAMILY_FAILED)?;
	Ok(Quintuple::new(src_addr, dst_addr, src_port, dst_port, skc_family))
}
