[package]
name = "deeptrace"
authors.workspace = true
categories = ["network", "cloud", "ebpf"]
description = "The DeepTrace project aims to provide deep observability for complex cloud-native applications."
edition.workspace = true
homepage = "https://github.com/DeepShield-AI/DeepTrace"
keywords = ["ebpf", "kernel", "linux", "network", "cloud"]
license = "MIT OR Apache-2.0"
publish.workspace = true
readme = "README.md"
repository = "https://github.com/DeepShield-AI/DeepTrace"
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true


[[bin]]
name = "deeptrace"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
observ-config.workspace = true
observ-core.workspace = true
observ-runtime.workspace = true
observ-sender.workspace = true
observ-synchronizer.workspace = true
observ-trace.workspace = true

codec.workspace = true

anyhow = { workspace = true, default-features = true }
arc-swap = { workspace = true, default-features = false }
clap = { workspace = true, default-features = false, features = ["derive", "std"] }
crossbeam-channel = { workspace = true }
env_logger.workspace = true
log = { workspace = true, default-features = false }
thiserror = { workspace = true, default-features = false }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "net", "signal", "fs", "io-std"], default-features = false }