# docker-compose.yml
version: '3.8'

services:
  redis:
    image: 47.97.67.233:5000/workload/redis
    container_name: redis-workload
    ports:
      - "6379:6379"

  memcached:
    image: 47.97.67.233:5000/workload/memcached
    container_name: memcached-workload
    ports:
      - "11211:11211"

  mongodb:
    image: 47.97.67.233:5000/workload/mongo:4.4.6
    container_name: mongo-workload
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
