[elastic]  # Elasticsearch related configuration
elastic_password = "xxx"         # Elasticsearch user password

[server]
ip  = "xxx"                      # The external IP address of the host running the DeepTrace server

# ========== agent1 configuration ==========
[[agents]]
  [agents.agent_info]  # Basic agent information
  agent_name = "xxx"           # Agent name
  user_name = "xxx"            # Username for SSH login
  host_ip = "xxx"              # Agent host IP address
  ssh_port = "xxx"             # SSH port
  host_password = "xxx"        # Host password

# ========== agent2 configuration ==========
# [[agents]]
#   [agents.agent_info]  # Basic agent information
#   agent_name = "xxx"           # Agent name
#   user_name = "xxx"            # Username for SSH login
#   host_ip = "xxx"              # Agent host IP address
#   ssh_port = "xxx"             # SSH port
#   host_password = "xxx"        # Host password