[package]
name = "observ-trace-common"

authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
std = []
user = ["std", "observ-core", "serde/std"]

[dependencies]
observ-core = { workspace = true, optional = true }
ebpf-common.workspace = true

aya-ebpf.workspace = true
num_enum = { workspace = true, default-features = false }
serde = { workspace = true, default-features = false, features = ["derive"] }

[lib]
path = "src/lib.rs"
