use super::consts::{MAX_INFER_PAYLOAD_SIZE, MAX_IOVEC_PAYLOAD_SIZE, MAX_PAYLOAD_SIZE};

pub const PAYLOAD_MASK: u32 = MAX_PAYLOAD_SIZE as u32 - 1;
pub const IOVEC_MASK: u32 = MAX_IOVEC_PAYLOAD_SIZE - 1;
pub const INFER_MASK: u32 = MAX_INFER_PAYLOAD_SIZE - 1;
