[package]
name = "agent"
version = "0.1.0"
authors = ["smore.ioki@gmail.com", "gyt22@mails.tsinghua.edu.cn"]
edition = "2024"
rust-version = "1.85.0"
description = "The DeepTrace project aims to provide deep observability for complex cloud-native applications."
readme = "README.md"
homepage = "https://github.com/DeepShield-AI/DeepTrace"
repository = "https://github.com/DeepShield-AI/DeepTrace"
license = "MIT OR Apache-2.0"
keywords = ["ebpf", "kernel", "linux", "network", "cloud"]
categories = ["network", "cloud", "ebpf"]
publish = false
default-run = "agent"
build = "build.rs"

[workspace]
resolver = "2"
members = ["."]
exclude = []
default-members = ["."]
package.authors = ["smore.ioki@gmail.com", "gyt22@mails.tsinghua.edu.cn"]
package.edition = "2024"
package.homepage = "https://github.com/DeepShield-AI/DeepTrace"
package.license = "MIT OR Apache-2.0"
package.rust-version = "1.85.0"
package.repository = "https://github.com/DeepShield-AI/DeepTrace"

[workspace.dependencies]
# ebpf
aya = { version = "0.13.1", default-features = false }
aya-ebpf = { version = "0.1.1", default-features = false }
aya-log = { version = "0.2.1", default-features = false }
aya-log-ebpf = { version = "0.1.1", default-features = false }
# common
trace_common = { path = "src/trace/common", default-features = false }
provenance_common = { path = "src/provenance/common", default-features = false }
# error
anyhow = { version = "1", default-features = false }
# serialization
serde = { version = "1.0.219", default-features = false }
serde_json = { version = "1.0.140", default-features = false }
# build
aya-build = { version = "0.1.2", default-features = false }
which = { version = "7.0.2", default-features = false }
# misc
## bit
bitflags = { version = "2.9.0", default-features = false }
## cpu
# core_affinity = { version = "0.8.3", default-features = false }
## docker
bollard = { version = "0.17.0", default-features = false }
## enum
num_enum = { version = "0.7.3", default-features = false }

[workspace.lints.clippy]
unused_trait_names = "warn"

[workspace.lints.rust]
unused-extern-crates = "warn"

[dependencies]
# common
trace_common = { workspace = true, features = ["user"] }
provenance_common = { workspace = true, features = ["user"] }
# communication
futures = { version = "0.3.31", default-features = false }
futures-util = { version = "0.3.31", default-features = false }
tokio-tungstenite = { version = "0.26.2", default-features = true }
# concurrency
arc-swap = { version = "1.7.1", default-features = false }
crossbeam-channel = { version = "0.5.15", default-features = true }
dashmap = { version = "7.0.0-rc2", default-features = false }
tokio = { version = "1.45.0", features = ["macros", "rt", "rt-multi-thread", "net", "signal", "fs", "io-std"], default-features = false }
# ebpf
aya = { workspace = true }
aya-log = { workspace = true }
# error
anyhow = { workspace = true, default-features = true }
thiserror = { version = "2.0.11", default-features = false }
# serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
# misc
## api
rocket = { version = "0.5.1", default-features = false, features = ["json"] }
## byte
bytes = { version = "1.9.0", default-features = true }
# cli
# `std` feature is currently required to build `clap`.
#
# See https://github.com/clap-rs/clap/blob/61f5ee5/clap_builder/src/lib.rs#L15.
clap = { version = "4.5.20", default-features = false, features = ["derive", "std"] }
## config
config = { version = "0.15.11", default-features = true }
## cpu
# core_affinity = { version = "0.8.3", default-features = false }
## docker
bollard = { workspace = true }
## elasticsearch
elasticsearch = { version = "8.17.0-alpha.1", default-features = false }
## k8s
# kube = { version = "0.99.0", features = ["ws"] }
# k8s-openapi = { version = "0.24.0", features = ["v1_29"] }
# logging
env_logger = { version = "0.11.5", default-features = false }
log = { version = "0.4.22", default-features = false }
## time
chrono = { version = "0.4.41", default-features = false, features = ["clock"] }
chrono-tz = { version = "0.10.3" }
# unix
libc = { version = "0.2.159", default-features = false }
## url
url = { version = "2.5.4", default-features = false }
## zip
flate2 = { version = "1.1.1", default-features = false, features = ["zlib-rs"] }

[build-dependencies]
anyhow = { workspace = true }
aya-build = { workspace = true }
# TODO(https://github.com/rust-lang/cargo/issues/12375): this should be an artifact dependency, but
# it's not possible to tell cargo to use `-Z build-std` to build it. We cargo-in-cargo in the build
# script to build this, but we want to teach cargo about the dependecy so that cache invalidation
# works properly.
#
# Note also that https://github.com/rust-lang/cargo/issues/10593 occurs when `target = ...` is added
# to an artifact dependency; it seems possible to work around that by setting `resolver = "1"` in
# Cargo.toml in the workspace root.
#
# Finally note that *any* usage of `artifact = ...` in *any* Cargo.toml in the workspace breaks
# workflows with stable cargo; stable cargo outright refuses to load manifests that use unstable
# features.
provenance-ebpf = { path = "src/provenance/ebpf" }
trace-ebpf = { path = "src/trace/ebpf" }

[[bin]]
name = "agent"
path = "src/main.rs"

# [profile.dev]
# opt-level = 3
# debug = false
# debug-assertions = false
# overflow-checks = false
# lto = true
# panic = "abort"
# incremental = false
# codegen-units = 1
# rpath = false

[profile.release]
panic = "abort"
opt-level = 3
# debug = 2
lto = true
codegen-units = 1