[package]
name = "procfs-integration-tests"
authors.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
observ-metric-common.workspace = true
observ-cpu.workspace = true
observ-memory.workspace = true
observ-disk.workspace = true
observ-network.workspace = true
observ-metric-utils.workspace = true

observ-fixtures.workspace = true
test-utils.workspace = true

anyhow.workspace = true
approx.workspace = true
chrono.workspace = true
clap.workspace = true
pretty_assertions.workspace = true
rand = "0.10.0-rc.0"
serde.workspace = true
serde_json.workspace = true
tempfile = "3.0"
tokio.workspace = true
uom.workspace = true

[[bin]]
name = "procfs_integration_tests"
path = "src/main.rs"
